---
- name: 01 Playbook to Add Common Criteria Policy & Login Hardening
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - /etc/ansible/clemea2024-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: 01a Task to Add Common Criteria Policy
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <aaa>
                  <common-criteria xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa">
                    <policy>COMMON-POLICY</policy>
                    <char-changes>3</char-changes>
                    <lower-case>1</lower-case>
                    <max-length>127</max-length>
                    <min-length>12</min-length>
                    <numeric-count>1</numeric-count>
                    <special-case>1</special-case>
                    <upper-case>1</upper-case>
                    <character-repetition>2</character-repetition>
                    <restrict-consecutive-letters/>
                  </common-criteria>
                </aaa>
              </native>
            </config>

    - name: 01b Task to Add Login Block and Login Logging
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <login>
                  <on-failure>
                    <log/>
                  </on-failure>
                  <on-success>
                    <log/>
                  </on-success>
                  <block-config>
                    <block-for>60</block-for>
                    <attempts>5</attempts>
                    <within>1</within>
                  </block-config>
                </login>
              </native>
            </config>

