---
- name: 01 Playbook to Add Common Criteria Policy
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - ~/clemea2024-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: 01a Task to Add Common Criteria Policy
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <aaa>
                  <new-model xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa"/>
                  <common-criteria xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa">
                    <policy>COMMON-POLICY</policy>
                    <char-changes>3</char-changes>
                    <max-length>127</max-length>
                    <min-length>12</min-length>
                    <restrict-consecutive-letters/>
                  </common-criteria>
                </aaa>
              </native>
            </config>

    - name: 01b Task to Add Common Criteria User
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <username>
                  <name>johnny-apples</name>
                  <privilege>15</privilege>
                  <secret>
                    <encryption>8</encryption>
                    <secret>$8$W1gdQsmGACDv8k$Nx/n2usXnOgVOgGu/We2TeUw2Ez3RoE8Y8s9X3eKxbs</secret>
                  </secret>
                  <common-criteria-policy xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa">
                    <common-criteria-policy>COMMON-POLICY</common-criteria-policy>
                  </common-criteria-policy>
                </username>
                <username>
                  <name>johnny-apples</name>
                </username>
              </native>
            </config>

