---
- name: 05 This Playbook will create an SNMPv3 Framework on an IOS XE Device
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - /etc/ansible/clemea2024-devnet-2111/vaults/ciscolive.vault
    - /etc/ansible/clemea2024-devnet-2111/vaults/encrypted-pass.vault

  tasks:
    - name: 05a Create Standard Access List Permitting Access to IOS XE SNMP Server
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <ip>
                  <access-list>
                    <standard xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-acl">
                      <name>snmp-access</name>
                      <access-list-seq-rule>
                        <sequence>10</sequence>
                        <permit>
                          <std-ace>
                            <ipv4-address-prefix>192.168.10.0</ipv4-address-prefix>
                            <mask>0.0.0.255</mask>
                          </std-ace>
                        </permit>
                      </access-list-seq-rule>
                    </standard>
                  </access-list>
                </ip>
              </native>
            </config>

    - name: 05b Create Read Only SNMPv3 View
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <view xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <name>snmp-v3-ReadOnly-View</name>
                    <mib>iso</mib>
                    <inc-exl>included</inc-exl>
                  </view>
                  <view xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <name>snmp-v3-ReadOnly-View</name>
                    <mib>iso</mib>
                  </view>
                </snmp-server>
              </native>
            </config>

    - name: 05c Create Read Write SNMPv3 View
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <view xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <name>snmp-v3-ReadWrite-View</name>
                    <mib>iso</mib>
                    <inc-exl>included</inc-exl>
                  </view>
                  <view xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <name>snmp-v3-ReadWrite-View</name>
                    <mib>iso</mib>
                  </view>
                </snmp-server>
              </native>
            </config>

    - name: 05d Create Read Only SNMPv3 Group
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <group xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <id>snmp-v3-ReadOnly</id>
                    <v3>
                      <security-level>priv</security-level>
                      <read>snmp-v3-ReadOnly-View</read>
                      <access>snmp-access</access>
                    </v3>
                  </group>
                </snmp-server>
              </native>
            </config>

    - name: 05e Create Read Write SNMPv3 Group
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <group xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <id>snmp-v3-ReadWrite</id>
                    <v3>
                      <security-level>priv</security-level>
                      <write>snmp-v3-ReadWrite-View</write>
                      <access>snmp-access</access>
                    </v3>
                  </group>
                </snmp-server>
              </native>
            </config>

    - name: 05f Create SNMPv3 Read Only User
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <user xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <names>
                      <username>willem-ReadOnly</username>
                      <grpname>snmp-v3-ReadOnly</grpname>
                      <v3>
                        <auth>
                          <sha>
                            <auth>
                              <authpass>{{ willem_auth_pass }}</authpass>
                              <priv>
                                <aes>
                                  <algo128>
                                    <privpass>
                                      <privpass>{{ willem_priv_pass }}</privpass>
                                      <access>snmp-access</access>
                                    </privpass>
                                  </algo128>
                                </aes>
                              </priv>
                            </auth>
                          </sha>
                        </auth>
                      </v3>
                    </names>
                    <names>
                      <username>willem-ReadOnly</username>
                      <grpname>snmp-v3-ReadOnly</grpname>
                    </names>
                  </user>
                </snmp-server>
              </native>
            </config>

    - name: Pause permit Config & NETCONF DB Sync
      pause:
        seconds: 15

    - name: 05g Create SNMPv3 Read Write User
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <user xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <names>
                      <username>kashvi-ReadWrite</username>
                      <grpname>snmp-v3-ReadWrite</grpname>
                      <v3>
                        <auth-config>
                          <sha-2>512</sha-2>
                          <password>{{ kashvi_auth_pass }}</password>
                          <priv-config>
                           <aes>
                              <algorithm>256</algorithm>
                              <password>{{ kashvi_priv_pass }}</password>
                              <access-config>
                                <acl-name>snmp-access</acl-name>
                              </access-config>
                            </aes>
                          </priv-config>
                        </auth-config>
                      </v3>
                    </names>
                    <names>
                      <username>kashvi-ReadWrite</username>
                      <grpname>snmp-v3-ReadWrite</grpname>
                    </names>
                  </user>
                </snmp-server>
              </native>
            </config>

