---
- name: 05 This Playbook will create an SNMPv3 Framework on an IOS XE Device
  hosts: iosxe
  connection: network_cli
  gather_facts: false

  vars_files:
    - /etc/ansible/clemea2024-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: 05b Create Read Only and Read Write SNMPv3 Views
      cisco.ios.ios_snmp_server:
        config:
          views:
            - name: snmp-v3-ReadOnly-View
              family_name: iso
              included: true
              
            - name: snmp-v3-ReadWrite-View
              family_name: iso
              included: true
