---
- name: Create SNMPv3 Framework on IOS XE Device
  hosts: iosxe
  gather_facts: false
  connection: network_cli

  vars_files:
    - /etc/ansible/clemea2024-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: Include IOS Role
      include_role:
        name: cisco.ios

    - name: Create SNMPv3 Views
      cisco.ios.ios_snmp_server:
        config:
          views:
            - name: snmp-v3-ReadOnly-View
              family_name: iso
              included: true

            - name: snmp-v3-ReadWrite-View
              family_name: iso
              included: true
