---
- name: 05 This Playbook will create an SNMPv3 Framework on an IOS XE Device
  hosts: iosxe
  gather_facts: false
  connection: network_cli

  #vars:
  #  ansible_network_os: cisco.ios.ios
  #  ansible_network_cli_ssh_type: libssh

  vars_files:
    - /etc/ansible/clemea2024-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: 05c Create Read Only and Read Write SNMPv3 Groups
      cisco.ios.ios_snmp_server:
        config:
          groups:
            - group: snmp-v3-ReadOnly
              version: v3
              version_option: priv
              acl_v4: snmp-access
              read: snmp-v3-ReadOnly-View

            - group: snmp-v3-ReadWrite
              version: v3
              version_option: priv
              acl_v4: snmp-access
              read: snmp-v3-ReadWrite-View
