---
- name: 05 This Playbook will create an SNMPv3 Framework on an IOS XE Device
  hosts: iosxe
  gather_facts: false
  connection: network_cli

  #vars:
  #  ansible_network_os: cisco.ios.ios
  #  ansible_network_cli_ssh_type: libssh

  vars_files:
    - /etc/ansible/clemea2024-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: 05d Create SNMPv3 Users
      cisco.ios.ios_snmp_server:
        config:
          users:
            - username: willem-ReadOnly
              group: snmp-v3-ReadOnly
              version: v3
              authentication:
                algorithm: sha
                password: ciscolive123
              encryption:
                priv: aes
                priv_option: 128
                password: ciscolive123
              acl_v4: snmp-access

            - username: kashvi-ReadWrite
              group: snmp-v3-ReadWrite
              version: v3
              authentication:
                algorithm: sha
                password: ciscolive123
              encryption:
                priv: aes
                priv_option: 128
                password: ciscolive123
              acl_v4: snmp-access
 