---
- name: Macsec-network-link
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - /etc/ansible/clemea2024-devnet-2111/vaults/ciscolive.vault
    - /etc/ansible/clemea2024-devnet-2111/vaults/encrypted-pass.vault

  tasks:
    - name: 06g Configure MACsec Network Link on the Interface
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <GigabitEthernet>
                    <name>1/0/1</name>
                    <macsec-option xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-switch">
                      <macsec>
                        <network-link/>
                      </macsec>
                    </macsec-option>
                  </GigabitEthernet>
                </interface>
              </native>
            </config>

