
# Ansible will need some basic information to make sure
# it can connect to the target device before attempting
# a NETCONF message. Ansible will look in the same directory
# as the playbook file for ansible.cfg.
#
# Nearly all parameters in ansible.cfg can be overridden
# with ansible-playbook command line flags.

# Example of basic ansible.cfg file
#
#[defaults]
#inventory = ./ansible_host
#host_key_checking = False
#remote_user = USERNAME_HERE

# Example of basic ansible_host file referred to in
# ansible.cfg inventory.
#
#[all:vars]
#ansible_connection=netconf
#ansible_password=PASSWORD_HERE
#
#[MY_HOST_NAME]
#IP_ADDRESS_HERE
#
- name : snmp-rw-user
  hosts: iosxe
  connection: netconf
  gather_facts: no

  vars_files:
    - /etc/ansible/clemea2024-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: snmp-rw-user
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <user xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <names>
                      <username>kashvi-ReadWrite</username>
                      <grpname>snmp-v3-ReadWrite</grpname>
                      <v3>
                        <auth-config>
                          <sha-2>512</sha-2>
                          <password>ciscolive123</password>
                          <priv-config>
                            <aes>
                              <algorithm>256</algorithm>
                              <password>ciscolive123</password>
                              <access-config>
                                <standard-acl/>
                              </access-config>
                            </aes>
                          </priv-config>
                        </auth-config>
                      </v3>
                    </names>
                    <names>
                      <username>kashvi-ReadWrite</username>
                      <grpname>snmp-v3-ReadWrite</grpname>
                    </names>
                  </user>
                </snmp-server>
              </native>
            </config>

