---
- name : snmp-group-nc
  hosts: iosxe
  connection: netconf
  gather_facts: no

  vars_files:
    - /etc/ansible/clemea2024-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: snmp-group-nc
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <group xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <id>snmp-v3-ReadOnly</id>
                    <v3>
                      <security-level>priv</security-level>
                      <read>snmp-v3-ReadOnly-View</read>
                    </v3>
                  </group>
                </snmp-server>
              </native>
            </config>

