---
- name : 05 This Playbook will create an SNMPv3 Framework on an IOS XE Device
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - /etc/ansible/clemea2024-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: 05b Create Read Only SNMPv3 View
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <view xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <name>snmp-v3-ReadOnly-View</name>
                    <mib>iso</mib>
                    <inc-exl>included</inc-exl>
                  </view>
                  <view xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <name>snmp-v3-ReadOnly-View</name>
                    <mib>iso</mib>
                  </view>
                </snmp-server>
              </native>
            </config>

    - name: 05b Create Read Write SNMPv3 View
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <view xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <name>snmp-v3-ReadWrite-View</name>
                    <mib>iso</mib>
                    <inc-exl>included</inc-exl>
                  </view>
                  <view xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <name>snmp-v3-ReadWrite-View</name>
                    <mib>iso</mib>
                  </view>
                </snmp-server>
              </native>
            </config>

    - name: 05c Create Read Only SNMPv3 Group
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <group xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <id>snmp-v3-ReadOnly</id>
                    <v3>
                      <security-level>priv</security-level>
                      <read>snmp-v3-ReadOnly-View</read>
                      <access>snmp-access</access>
                    </v3>
                  </group>
                </snmp-server>
              </native>
            </config>

    - name: 05c Create Read Write SNMPv3 Group
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <group xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <id>snmp-v3-ReadWrite</id>
                    <v3>
                      <security-level>priv</security-level>
                      <write>snmp-v3-ReadWrite-View</write>
                      <access>snmp-access</access>
                    </v3>
                  </group>
                </snmp-server>
              </native>
            </config>

    - name: 05d Create SNMPv3 Read Only User
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <user xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <names>
                      <username>willem-ReadOnly</username>
                      <grpname>snmp-v3-ReadOnly</grpname>
                      <v3>
                        <auth>
                          <sha>
                            <auth>
                              <authpass>ciscolive123</authpass>
                              <priv>
                                <aes>
                                  <algo128>
                                    <privpass>
                                      <privpass>ciscolive123</privpass>
                                      <access>snmp-access</access>
                                    </privpass>
                                  </algo128>
                                </aes>
                              </priv>
                            </auth>
                          </sha>
                        </auth>
                      </v3>
                    </names>
                    <names>
                      <username>willem-ReadOnly</username>
                      <grpname>snmp-v3-ReadOnly</grpname>
                    </names>
                  </user>
                </snmp-server>
              </native>
            </config>

    - name: Pause for 5 seconds
      pause:
        seconds: 5
  
    - name: 05d Create SNMPv3 Read Write User
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <user xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <names>
                      <username>kashvi-ReadWrite</username>
                      <grpname>snmp-v3-ReadWrite</grpname>
                      <v3>
                        <auth-config>
                          <sha-2>512</sha-2>
                          <password>ciscolive123</password>
                          <priv-config>
                           <aes>
                              <algorithm>256</algorithm>
                              <password>ciscolive123</password>
                              <access-config>
                                <acl-name>snmp-access</acl-name>
                              </access-config>
                            </aes>
                          </priv-config>
                        </auth-config>
                      </v3>
                    </names>
                    <names>
                      <username>kashvi-ReadWrite</username>
                      <grpname>snmp-v3-ReadWrite</grpname>
                    </names>
                  </user>
                </snmp-server>
              </native>
            </config>

