
# Ansible will need some basic information to make sure
# it can connect to the target device before attempting
# a NETCONF message. Ansible will look in the same directory
# as the playbook file for ansible.cfg.
#
# Nearly all parameters in ansible.cfg can be overridden
# with ansible-playbook command line flags.

# Example of basic ansible.cfg file
#
#[defaults]
#inventory = ./ansible_host
#host_key_checking = False
#remote_user = USERNAME_HERE

# Example of basic ansible_host file referred to in
# ansible.cfg inventory.
#
#[all:vars]
#ansible_connection=netconf
#ansible_password=PASSWORD_HERE
#
#[MY_HOST_NAME]
#IP_ADDRESS_HERE
#
- name : snmp-access-list
  hosts: iosxe
  connection: netconf
  gather_facts: no

  vars_files:
    - /etc/ansible/clemea2024-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: snmp-access-list
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <ip>
                  <access-list>
                    <standard xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-acl">
                      <name>snmp-access</name>
                      <access-list-seq-rule>
                        <sequence>10</sequence>
                        <permit>
                          <std-ace>
                            <ipv4-address-prefix>192.168.10.0</ipv4-address-prefix>
                            <mask>0.0.0.255</mask>
                          </std-ace>
                        </permit>
                      </access-list-seq-rule>
                    </standard>
                  </access-list>
                </ip>
              </native>
            </config>

