---
- name : 05 This Playbook will create an SNMPv3 Framework on an IOS XE Device
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
    - /etc/ansible/clemea2024-devnet-2111/vaults/ciscolive.vault

  tasks:
    - name: 05b Create Read Only SNMPv3 View
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <view xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <name>snmp-v3-ReadOnly-View</name>
                    <mib>iso</mib>
                    <inc-exl>included</inc-exl>
                  </view>
                  <view xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <name>snmp-v3-ReadOnly-View</name>
                    <mib>iso</mib>
                  </view>
                </snmp-server>
              </native>
            </config>

    - name: 05b Create Read Write SNMPv3 View
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <view xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <name>snmp-v3-ReadWrite-View</name>
                    <mib>iso</mib>
                    <inc-exl>included</inc-exl>
                  </view>
                  <view xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <name>snmp-v3-ReadWrite-View</name>
                    <mib>iso</mib>
                  </view>
                </snmp-server>
              </native>
            </config>

    - name: 05c Create Read Only SNMPv3 Group
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <group xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <id>snmp-v3-ReadOnly</id>
                    <v3>
                      <security-level>priv</security-level>
                      <read>snmp-v3-ReadOnly-View</read>
                    </v3>
                  </group>
                </snmp-server>
              </native>
            </config>

    - name: 05c Create Read Write SNMPv3 Group
      netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <snmp-server>
                  <group xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-snmp">
                    <id>snmp-v3-ReadWrite</id>
                    <v3>
                      <security-level>priv</security-level>
                      <write>snmp-v3-ReadWrite-View</write>
                    </v3>
                  </group>
                </snmp-server>
              </native>
            </config>

